### ISSUE TITLE
enable cubx-maps-element component to output selected marker

### ISSUE THREAD

**Issue by pwrinc** [iCubbles/cubx-maps#8]
Add new output slot `selectedMarker` which should hold a copy of the whole selected marker config item (from `list` array in `markers` inputSlot). 

- [x] Per default it should be `undefined`.
- [x] only should hold value if marker is currently active, thus it needs to be unset if marker gets closed again

**Comment by edwingamboa** [comment]
An output slot called `selectedElement` was created. An element can be a marker, circle, rectangle, polygon or polyline. `selectedElement` represents the currently selected (clicked) element. It is a JSON object like 
```javascript
{
   element: the element as provided through an input slot, 
   type: 'marker |circle | rectangle | polygon | polyline'
} 
// e.g., 
{ 
   element: { latlng: [ 51.5, -0.09 ], leafLetOptions: { title: 'Fixed Marker' } },
   type: 'marker'
}
````
Since leaflet does not have events like selected or deselected, the click event was employed as follows:
*  If an element is clicked, the `selectedElement` slot using the info of the element (provided through input slots).
* if the map is clicked `selectedElement` is set to undefined
